### ISSUE TITLE
Post Design Team’s descriptive values into their team page on the wiki

### ISSUE THREAD

**Issue by dperegolise** [Police-Data-Accessibility-Project/organizational-issues#46]
Found here: https://policeaccessibility.slack.com/files/U0143RU9K4N/F015GP5K000/pdap_values_-_google_docs.pdf

**Comment by zmacks** [comment]
@dperegolise I made updates to this page: https://www.reddit.com/r/DataPolice/wiki/teams/recognition 

Let me know if the values seem a bit out of place. If so, maybe we can create subteam pages in the wiki for additional information like this.

**Comment by dperegolise** [comment]
@zmacks No it looks fine to me, thanks!
