### ISSUE TITLE
Limit chatter in #announcements

### ISSUE THREAD

**Issue by jlintag** [Police-Data-Accessibility-Project/organizational-issues#67]
If there is a way to limit posts outside of leadership in #announcements, that'd be great. We want to keep it generally clean so that people that want to get caught up won't get bogged down with more information than needed

I think it's ok to still allow people to reply to posts in threads though, so if that's possible, that'd be great

**Comment by zgoulson** [comment]
On the standard plan you can only restrict posting permissions on the #_general. I think that replies would be allowed though even if posting is restricted.
